### ISSUE TITLE
Breakout Backend GLES class

### ISSUE THREAD

**Issue by schell** [ziocroc/Ombra#1]
It would be great to breakout the GLES class that wraps OpenGL/WebGL in https://github.com/ziocroc/Ombra/blob/master/Graphics/Rendering/Ombra/Backend.hs. If this were a separate repo, other projects could use it (without depending on Ombra entirely). Either way, thanks!

**Comment by schell** [comment]
Similarly, the two backends could also be broken out, I guess all of them together. This is an abstraction over OpenGL/WebGL that has been needed for a long time.

**Comment by lprez** [comment]
Those modules were written specifically to work with the rest of the library, and this is reflected in many things:
- They use Ombra vector and matrix types
- They require and provide the same GL extensions that I used in Ombra
- Some functions are missing
- They only provide the instances I needed

Even after fixing all those things, I still believe it wouldn't be a good idea, the GLES class is more of an hack than an abstraction to me. I'd rather rewrite everything from scratch if I had to release them as an independent library.

**Comment by schell** [comment]
Understood. How would you abstract over the two? Would you provide a record? If I may use your code (and thoughts) as a starting point I might do this myself.

**Comment by lprez** [comment]
I'd do it the same way it is now, with a nullary type class, but I would make the API based on the least powerful one (WebGL) and provide extensions as separate, optional classes. The nullary class method lets you separate the abtract API from the implementations, which is what you want if I understood correctly. The biggest problem would be providing an uniform and efficient interface to manipulate certain types like float arrays, the current one is not generic enough and uses those Ombra vectors and matrices as I said.

**Comment by schell** [comment]
Okay, thanks - I have to read up on nullary type classes.

**Comment by schell** [comment]
Got it - simple enough.

**Comment by schell** [comment]
@ziocroc just to pick your brain a bit more - why use a nullary class instead of something like:
```haskell
class MonadGL a where
  data M a :: * -> *
  type GLEnum a
  glActiveTexture :: GLEnum a -> (M a) ()
  ...
```
The benefit I see here is that you can then keep from having to supply a `ctx` to every gl call. Thoughts? Does this have performance considerations?

**Comment by lprez** [comment]
To get rid of the context argument I just used a Reader monad transformer (see [GL.hs](https://github.com/ziocroc/Ombra/blob/master/Graphics/Rendering/Ombra/Internal/GL.hs)), but if your solution works well then I prefer it, I don't really like nullary type classes because of the little control you have over instances import. I don't know about performance.

**Comment by schell** [comment]
I see - thanks for the pointers!
