### ISSUE TITLE
Cabal can't find source for Graphics/Rendering/Ombra/Backend/WebGL

### ISSUE THREAD

**Issue by nathantalewis** [ziocroc/Ombra#3]
Hello, I'm trying to build Ombra using ghcjs 0.2.1 with ghc 8.0.2. It builds fine up to commit 98b70899e250203c7a3873d9df06c18c17aee85d, but after that it complains about not having a cabal file for a handful of commits, then when the cabel file is added in a later commit the build fails with the following error:
```
    Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9008011_ghc-8.0.2: can't find
    source for Graphics/Rendering/Ombra/Backend/WebGL in .,
    .stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs/build/autogen
```

**Comment by lprez** [comment]
I readded the WebGL backend with e14b7a5, did you try to build it after that?
By the way I just realized that two modules were missing from this repo (not the WebGL ones), with the last commit it should work fine.

**Comment by nathantalewis** [comment]
It looks like those two missing modules were the culprits. It's building fine with the latest commit.

Thanks!
